
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  pool: 25
  prepared_statements: false

test:
  <<: *default
  database: brews-and-grub-test

development:
  <<: *default
  host:  localhost
  database: brews-and-grub-development

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  reaping_frequency: <%= ENV['DB_REAP_FREQ'] || 10 %>
